sns/urls.py
from django.urls import path

from . import views, create_tables

app_name = 'sns'
urlpatterns = [
    path('', views.register, name='register'),
    path('login', views.login, name='login'),
    path('interface', views.interface, name='interface'),
    path('settings', views.settings, name='settings'),
    path('feed', views.feed, name='feed'),
    path('toggle', views.toggle, name='toggle'),
    path('wordfilter', views.wordfilter, name='wordfilter'),
    path('intensity_slider', views.intensity_slider, {'with_examples': False}, name='intensity_slider'),
    path('intensity_slider/with_examples', views.intensity_slider, {'with_examples': True}, name='intensity_slider_with_examples'),
    path('proportion_slider', views.proportion_slider, {'with_examples': False}, name='proportion_slider'),
    path('proportion_slider/with_examples', views.proportion_slider, {'with_examples': True}, name='proportion_slider_with_examples'),
    path('create_tables', create_tables.create_tables),
]

surveysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('sns.urls', 'sns'), namespace='sns')),
    *static('static/', document_root=settings.STATIC_ROOT)
]

sns/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.

class Comment(models.Model):
    text = models.TextField()
    toxicity_score = models.FloatField()
    author = models.CharField(default = 'Test Author', max_length=100)
    author_name = models.CharField(default = 'Test Author', max_length=100)
    pub_date = models.DateField('date published', default = now)
    num_likes = models.IntegerField(default = 0)
    num_comments = models.IntegerField(default = 0)
    num_retweets = models.IntegerField(default = 0)
    url = models.URLField(blank=True, null=True)
    twitter_id = models.CharField(blank=True, null=True, max_length=100)

class Participant(models.Model):

    INTERFACE_CHOICES = (
        ("1", "A"),
        ("2", "B"),
        ("3", "C"),
        ("4", "D"),
    )

    username = models.CharField(max_length=100, blank=True, null=True)
    turker_id = models.CharField(max_length=100, blank=True, null=True)
    setting = models.CharField(
        max_length=2,
        choices = INTERFACE_CHOICES,
        default = "1"
        )

    def resetToggle(self):
        toggleSetting, _ = ToggleSetting.objects.get_or_create(participant = self)
        toggleSetting.filter_toxic = False
        toggleSetting.save()

    def resetWordFilter(self):
        wordFilterSetting, _ = WordFilterSetting.objects.get_or_create(participant = self)
        wordFilterSetting.word_filters = ''
        wordFilterSetting.save()       

    def resetIntensitySlider(self):
        sliderSetting, _ = IntensitySliderSetting.objects.get_or_create(participant = self)
        sliderSetting.slider_level = 1
        sliderSetting.save()     

    def resetProportionSlider(self):
        sliderSetting, _ = ProportionSliderSetting.objects.get_or_create(participant = self)
        sliderSetting.slider_level = 1
        sliderSetting.save()                        

class ToggleSetting(models.Model):
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)
    filter_toxic = models.BooleanField(default = False)

class WordFilterSetting(models.Model):
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)
    word_filters = models.TextField(blank=True, null=True)

class IntensitySliderSetting(models.Model):

    class SliderChoices(models.IntegerChoices):
      NONE = 1
      A_LITTLE = 2
      SOME = 3
      MORE = 4
      A_LOT = 5

    slider_level = models.IntegerField(
        choices = SliderChoices.choices,
        default = 1
    )
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)

class ProportionSliderSetting(models.Model):

    class SliderChoices(models.IntegerChoices):
      NONE = 1
      A_LITTLE = 2
      SOME = 3
      MORE = 4
      A_LOT = 5

    slider_level = models.IntegerField(
        choices = SliderChoices.choices,
        default = 1
    )
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)    

sns/forms.py
from django import forms
from .widgets import SemanticScale
from .models import Participant, WordFilterSetting, IntensitySliderSetting, ProportionSliderSetting

class ParticipantForm(forms.ModelForm):
  id = forms.CharField()
  class Meta:
    model = Participant
    fields = [ "id", "username", "turker_id" ]


class WfForm(forms.ModelForm):
  word_filters = forms.CharField(
    required=False,
    widget=forms.Textarea(
      attrs={
      "placeholder": "Eg. Apple, Orange, Pear",
      "class": "textFilter-input",
      }
    ),
  )

  class Meta:
    model = WordFilterSetting
    fields = [ "word_filters" ]

class IntensitySliderForm(forms.ModelForm):
  slider_level = forms.IntegerField(
    widget = SemanticScale,
    max_value = 5,
    min_value = 1
  )

  class Meta:
    model = IntensitySliderSetting
    fields = [ "slider_level" ]

class ProportionSliderForm(forms.ModelForm):
  slider_level = forms.IntegerField(
    widget = SemanticScale,
    max_value = 5,
    min_value = 1
  )

  class Meta:
    model = ProportionSliderSetting
    fields = [ "slider_level" ]

class InterfaceForm(forms.ModelForm):
  setting = forms.CharField(
    widget=forms.RadioSelect(
      choices = Participant.INTERFACE_CHOICES
    ),
  )

  class Meta:
    model = Participant
    fields = [ "setting" ]

sns/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, reverse
from django.template.loader import render_to_string
from django.template import RequestContext
from .models import Comment, Participant, ToggleSetting, WordFilterSetting, IntensitySliderSetting, ProportionSliderSetting
from .forms import WfForm, IntensitySliderForm, ProportionSliderForm, InterfaceForm, ParticipantForm
import json, re
from random import shuffle

# Create your views here.
MAX_COMMENTS = 30

def register(request):
  if request.method == 'POST':
    action = request.POST.get('action', '')
    if action == 'New User':
      participant = Participant.objects.create()
      request.session['participant_id'] = participant.id
      return HttpResponseRedirect(reverse('sns:feed'))
    elif action == 'Existing User':
      return HttpResponseRedirect(reverse('sns:login'))
  # form = LoginForm()
  return render(request, "sns/is_new_user.html", {'uid': '?'})

def login(request):
  if request.method == 'POST':
    form = ParticipantForm(request.POST)
    if form.is_valid():
      if ('id' in form.cleaned_data):
        participant_id = form.cleaned_data['id']
        participant = Participant.objects.get(id = participant_id)
        request.session['participant_id'] = participant.id
        return HttpResponseRedirect(reverse('sns:feed'))
      else:
        return HttpResponseRedirect(reverse('sns:login'))
  form = ParticipantForm()
  return render(request, "sns/get_user.html", {'form': form, 'uid': '?'})

def getParticipantFromSession(request):
  try:
    participant = Participant.objects.get(id=request.session['participant_id'])
  except (KeyError, Participant.DoesNotExist):
    participant = None
  return participant

def get_matched_comments(word_filters):
  comments = Comment.objects.all()
  if (not(word_filters == '' or word_filters is None)):
    matched_comment_ids = []
    for comment in comments:
      lookups = []
      rules = word_filters.strip().split(',')
      for rule in rules:
        rule = rule.strip()
        lookup = re.search(r'\b({})\b'.format(rule), comment.text, re.IGNORECASE)
        lookups.append(lookup)
      if any(lookups):
        matched_comment_ids.append(comment.id)
    comments = Comment.objects.exclude(id__in = matched_comment_ids)
  if (len(comments) > MAX_COMMENTS):
    comments = comments[:MAX_COMMENTS]
  return comments

def settingsPage(setting):
  if (setting == "1"):
    return HttpResponseRedirect(reverse('sns:toggle'))
  elif (setting == "2"):
    return HttpResponseRedirect(reverse('sns:wordfilter'))
  elif (setting == "3"):
    return HttpResponseRedirect(reverse('sns:intensity_slider'))
  elif (setting == "4"):
    return HttpResponseRedirect(reverse('sns:proportion_slider'))

def interface(request):
  participant = getParticipantFromSession(request)

  if request.method == 'POST':
    # create a form instance and populate it with data from the request:
    form = InterfaceForm(request.POST)
    # check whether it's valid:
    if form.is_valid():
      setting = form.cleaned_data['setting']
      participant.setting = setting
      participant.save()
      return settingsPage(setting)
  else:
    form = InterfaceForm(initial={'setting': participant.setting})
    return render(request, "sns/interface.html", {'form': form, 'uid': participant.id})

def settings(request):
  participant = getParticipantFromSession(request)
  if participant is None:
    return HttpResponseRedirect(reverse('sns:register'))
  setting = participant.setting
  return settingsPage(setting)

def getCommentsFromSets(setList):
  idList = []
  for l in setList:
    idList += [comment.id for comment in l]
  comments = Comment.objects.filter(id__in = idList)
  return comments

def get_slider_comments(slider_type, slider_level):
  if (slider_type == 'intensity'):
    if (slider_level == 1):
      first_set = Comment.objects.filter(toxicity_score__gte = 0.2)
      second_set = Comment.objects.filter(toxicity_score__lt = 0.2)[:10]
      return getCommentsFromSets([first_set, second_set])
    elif (slider_level == 2):
      first_set = Comment.objects.filter(toxicity_score__gte = 0.2, toxicity_score__lt = 0.8)
      second_set = Comment.objects.filter(toxicity_score__lt = 0.2)[:15]
      return getCommentsFromSets([first_set, second_set])
    elif (slider_level == 3):
      first_set = Comment.objects.filter(toxicity_score__gte = 0.2, toxicity_score__lt = 0.6)
      second_set = Comment.objects.filter(toxicity_score__lt = 0.2)[:20]
      return getCommentsFromSets([first_set, second_set])
    elif (slider_level == 4):
      first_set = Comment.objects.filter(toxicity_score__gte = 0.2, toxicity_score__lt = 0.4)
      second_set = Comment.objects.filter(toxicity_score__lt = 0.2)[:25]
      return getCommentsFromSets([first_set, second_set])
    elif (slider_level == 5):
      return Comment.objects.filter(toxicity_score__lt = 0.2)[:30]

  elif (slider_type == 'proportion'):
    if (slider_level == 1):
      first_set = Comment.objects.filter(toxicity_score__gte = 0.2).order_by('num_likes')
      second_set = Comment.objects.filter(toxicity_score__lt = 0.2)[:10]
      return getCommentsFromSets([first_set, second_set])
    elif (slider_level == 2):
      first_set = Comment.objects.filter(toxicity_score__gte = 0.2).order_by('num_likes')[:15]
      second_set = Comment.objects.filter(toxicity_score__lt = 0.2)[:15]
      return getCommentsFromSets([first_set, second_set])
    elif (slider_level == 3):
      first_set = Comment.objects.filter(toxicity_score__gte = 0.2).order_by('num_likes')[:10]
      second_set = Comment.objects.filter(toxicity_score__lt = 0.2)[:20]
      return getCommentsFromSets([first_set, second_set])
    elif (slider_level == 4):
      first_set = Comment.objects.filter(toxicity_score__gte = 0.2).order_by('num_likes')[:5]
      second_set = Comment.objects.filter(toxicity_score__lt = 0.2)[:25]
      return getCommentsFromSets([first_set, second_set])
    elif (slider_level == 5):
      return Comment.objects.filter(toxicity_score__lt = 0.2)[:30]

def feed(request):
  participant = getParticipantFromSession(request)
  if participant is None:
    return HttpResponseRedirect(reverse('sns:register'))
  print ("setting:", participant.setting)
  if (participant.setting == "1"):
    participant.resetWordFilter()
    participant.resetIntensitySlider()
    participant.resetProportionSlider()
    toggleSetting, _ = ToggleSetting.objects.get_or_create(participant = participant)
    filter_toxic = toggleSetting.filter_toxic
    if (filter_toxic):
      comments = Comment.objects.filter(toxicity_score__lt = 0.2)[:MAX_COMMENTS]
    else:
      comments = Comment.objects.all()[:MAX_COMMENTS]
  elif (participant.setting == "2"):
    participant.resetToggle()
    participant.resetIntensitySlider()
    participant.resetProportionSlider()
    wordFilterSetting, _ = WordFilterSetting.objects.get_or_create(participant = participant)
    word_filters = wordFilterSetting.word_filters
    comments = get_matched_comments(word_filters)
  elif (participant.setting == "3"):
    participant.resetToggle()
    participant.resetWordFilter()
    participant.resetProportionSlider()
    sliderSetting, _ = IntensitySliderSetting.objects.get_or_create(participant = participant)
    slider_level = sliderSetting.slider_level
    print ("slider level:", slider_level)
    comments = get_slider_comments('intensity', slider_level)
  elif (participant.setting == "4"):
    participant.resetToggle()
    participant.resetWordFilter()
    participant.resetIntensitySlider()
    sliderSetting, _ = ProportionSliderSetting.objects.get_or_create(participant = participant)
    slider_level = sliderSetting.slider_level
    comments = get_slider_comments('proportion', slider_level)

  return render(request, "sns/feed.html", {'comments': comments, 'uid': participant.id})

def toggle(request):
  participant = getParticipantFromSession(request)
  if participant is None:
    return HttpResponseRedirect(reverse('sns:register'))
  toggleSetting, _ = ToggleSetting.objects.get_or_create(participant = participant)
  if request.method =='POST':
    post_value = request.POST['filter_toxic']
    toggleSetting.filter_toxic = post_value == 'true'
    toggleSetting.save()
    response = {
      'message': 'Your changes have been saved.'
    }
    return HttpResponse(json.dumps(response), content_type='application/json')
  else:
    return render(request, "sns/toggle.html", {'toggleSetting': toggleSetting, 'uid': participant.id})

def wordfilter(request):
  participant = getParticipantFromSession(request)
  if participant is None:
    return HttpResponseRedirect(reverse('sns:register'))
  wfSetting, _ = WordFilterSetting.objects.get_or_create(participant = participant)

  if request.method == 'POST':
    # create a form instance and populate it with data from the request:
    form = WfForm(request.POST)
    # check whether it's valid:
    if form.is_valid():
      word_filters = form.cleaned_data['word_filters']
      wfSetting.word_filters = word_filters
      wfSetting.save()
      response = {
        'message': 'Your changes have been saved.'
      }

      return HttpResponse(json.dumps(response), content_type='application/json')

  else:
    form = WfForm(initial={'word_filters': wfSetting.word_filters})
    return render(request, "sns/wordfilter.html", {'form': form, 'uid': participant.id})


def intensity_slider(request, **kwargs):
  with_examples = kwargs['with_examples']
  participant = getParticipantFromSession(request)
  if participant is None:
    return HttpResponseRedirect(reverse('sns:register'))
  sliderSetting, _ = IntensitySliderSetting.objects.get_or_create(participant = participant)
  show_alert = False

  if request.method == 'POST':
    form = IntensitySliderForm(request.POST)
    if form.is_valid():
      slider_level = form.cleaned_data['slider_level']

sns/templates/sns/feed.html
{% extends "sns/page_base.html" %}


{% load static %}
{% block scripts %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
{% endblock scripts %}

{% block content %}
  <!-- MIDDLE-CONTAINER -->
  <div class="middle-container container posts-container">
    <div class="tweets block">
      <!-- SOCIAL MEDIA FEED -->
      <h1 class="titular"><span class="icon"></span>Latest Posts</h1>
      {% for comment in comments %}
      <div class="tweet">
        <div class="profile">
          <img class="profile-picture" alt="Profile Picture" src="http://www.clker.com/cliparts/f/a/0/c/1434020125875430376profile-hi.png">
        </div>
        <div class="tweet-body">
          <div class="metadata">
            <a class="" href="">
              {{ comment.author_name }}
              <span class="handle">@{{ comment.author }}</span>
              <span class="time-ago scnd-font-color">{{ comment.pub_date }}</span>
            </a>
          </div>
          <div class="content">
            <p>
              {{comment.text}}
            </p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

sns/templates/sns/get_user.html
{% extends "sns/page_base.html" %}


{% load static %}

{% block scripts %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
{% endblock scripts %}

{% block content %}

<!-- MIDDLE-CONTAINER -->
<div class="middle-container container">
  <div class="togglediv block">
    <h1 class="titular"><span class="icon"></span>Enter Your User ID</h1>
    <div class="togglequestion">
      <h2>My User ID:</h2>
      <form action="" method="post" id="wf-form">
        {% csrf_token %}
        <formgroup>
          {{ form.id.errors }}
          {{ form.id }}
        </formgroup>

        <input type="submit" class="btn btn-primary save-button" value="Submit" />
      </form>
    </div>
  </div>
</div>
{% endblock content %}

sns/templates/sns/int_slider.html
{% extends "sns/page_base.html" %}


{% load static %}

{% block scripts %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'sns/slider.css' %}">
{% endblock scripts %}

{% block content %}

<!-- MIDDLE-CONTAINER -->
<div class="middle-container container">
  <div class="togglediv block">
    <h1 class="titular"><span class="icon"></span>Choose Your Moderation Setting</h1>
    <div class="togglequestion">
      <h2>  Filter out inappropriate posts based on the level you select:  </h2>
      <form action="" method="post" id="slider-form">
        {% csrf_token %}
        <formgroup>
          {{ form.slider_level.errors }}

          {{ form.slider_level }}
        </formgroup>
        <input type="submit" class="btn btn-primary save-button" value="Save" />
      </form>
      <div class="result"><span id="result"></span></div>
      <p class="instruction">  Comments more toxic than your selected level will be filtered out of your feed.  </p>
    </div>

  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#slider-form').submit(function(e){
    console.log("came here");
    $.post("{% url 'sns:int_slider' %}",
      $(this).serialize(),
      function(data){
        var self = document.getElementById("result");
        self.innerText = data.message;
        setTimeout(function() {
            self.innerText = '';
        }, 2000);
      });
     e.preventDefault();
   });
});
</script> -->


{% endblock content %}

sns/templates/sns/interface.html
{% extends "sns/page_base.html" %}


{% load static %}

{% block scripts %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'sns/wordfilter.css' %}">
{% endblock scripts %}

{% block content %}

<!-- MIDDLE-CONTAINER -->
<div class="middle-container container">
  <div class="togglediv block">
    <h1 class="titular"><span class="icon"></span>Choose Your Settings Interface</h1>
    <div class="togglequestion">
      <h2>  Select the personal moderation setting type you want to test:  </h2>
      <form action="" method="post" id="wf-form">
        {% csrf_token %}
        <formgroup>
          {{ form.setting.errors }}

          {{ form.setting }}
        </formgroup>
        <input type="submit" class="btn btn-primary save-button" value="Submit" />
      </form>
      <div class="result"><span id="result"></span></div>
    </div>

  </div>
</div>
{% endblock content %}

sns/templates/sns/is_new_user.html
{% extends "sns/page_base.html" %}
{% load static %}

{% block scripts %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
{% endblock scripts %}


{% block content %}

<!-- MIDDLE-CONTAINER -->
<div class="middle-container container">
  <div class="togglediv block">
    <h1 class="titular"><span class="icon"></span>New or Existing User?</h1>
    <div class="togglequestion">
      <p>
        If you are a new participant, please press the "New User" button.<br/>
        If you are a returning participant, please press the "Existing User" button.
      </p>
      <form action="" method="post" id="wf-form">
        {% csrf_token %}
        <div class="centered-button-group">
          <input name="action" type="submit" class="btn btn-primary save-button" value="New User" />
          <input name="action" type="submit" class="btn btn-primary save-button" value="Existing User" />
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

sns/templates/sns/page_base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <title> Your Social Network Site</title>

  <!-- internal libraries -->
  {% block scripts %}
  {% endblock scripts %}
  <link rel="stylesheet" href="{% static 'sns/base.css' %}">
</head>
<body>
  <div class="main-container container">
    <!-- HEADER -->
    <header class="block">
      <ul class="header-menu horizontal-list">
        <li>
           <a class="header-menu-tab" href="{% url 'sns:feed' %}"><span class="icon fontawesome-user scnd-font-color"></span>Feed</a>
        </li>
        <li>
          <a class="header-menu-tab" href="{% url 'sns:settings' %}"><span class="icon entypo-cog scnd-font-color"></span>Settings</a>
        </li>
        <li style="float: right;">
          <div class="profile-menu">
            <p>Me ({{ uid }})<a href="#26"><span class="entypo-down-open scnd-font-color"></span></a></p>
            <div class="profile-picture small-profile-picture">
              <img width="40px" alt="Profile Picture" style="vertical-align: top" src="http://www.clker.com/cliparts/f/a/0/c/1434020125875430376profile-hi.png">
            </div>
          </div>
        </li>
        <li style="float: right;">
          <a class="header-menu-tab" href="{% url 'sns:interface' %}"><span class="icon fontawesome-cogs scnd-font-color"></span>Change Moderation System</a>
        </li>
      </ul>
    </header>
    {% block content %}
    {% endblock content %}
  </div>
</body>
</html>

sns/templates/sns/semantic_slider.html
{% extends "sns/page_base.html" %}
{% load static %}

{% block scripts %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'widgets/slider.css' %}">
  <script src="{% static 'widgets/slider.js' %}"></script>
{% endblock scripts %}

{% block content %}
<!-- MIDDLE-CONTAINER -->
<div class="middle-container container">
  <div class="togglediv block">
    <h1 class="titular"><span class="icon"></span>Choose Your Moderation Setting</h1>
    <div class="togglequestion">
      <h2>  Filter out inappropriate posts based on the level you select:  </h2>
      <form action="" method="post" id="slider-form">
        {% csrf_token %}
        <formgroup>
          {% if slider_mode == 'intensity' %}
            <div class="levels">
              <div class="level">Nothing</div>
              <div class="level">Very Toxic</div>
              <div class="level">Toxic</div>
              <div class="level">Somewhat Toxic</div>
              <div class="level">Mildly Toxic</div>
            </div>
          {% else %}
            <div class="levels">
              <div class="level">No Moderation</div>
              <div class="level">A Little Moderation</div>
              <div class="level">Some Moderation</div>
              <div class="level">More Moderation</div>
              <div class="level">A Lot of Moderation</div>
            </div>
          {% endif %}
          <div class="leveled-slider">
            {{ form.slider_level }}
          </div>
          <div class="level-explanation" id="slider-explanation">
            This will be filled once the slider is set.
            You should not see this message.
          </div>
          <div class="level-examples" id="slider-examples"></div>
          {% if with_examples %}
            <div id="examples-mode" style="display: none;">on</div>
          {% else %}
            <div id="examples-mode" style="display: none;">off</div>
          {% endif %}
          <div id="slider-mode" style="display: none;">{{ slider_mode }}</div>
        </formgroup>
        <input type="submit" class="btn btn-primary save-button" value="Save" />
      </form>
      {% if show_alert %}
        <div class="result"><span id="result">Your changes have been saved!</span></div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

sns/templates/sns/toggle.html
{% extends "sns/page_base.html" %}


{% load static %}

{% block scripts %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock scripts %}


{% block content %}

<!-- MIDDLE-CONTAINER -->
<div class="middle-container container">
  <div class="togglediv block">
    <h1 class="titular"><span class="icon"></span>Choose Your Moderation Setting</h1>
    <div class="togglequestion">

      <h2>  Your setting for toxic content:  </h2>

      <div class="form-check form-switch">
        <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" {% if toggleSetting.filter_toxic %} checked {% endif %} />
        <label class="form-check-label" style="color:white" for="flexSwitchCheckChecked">Filter out/censor all or no messages with toxic content</label>
      </div>

        <div class="result"><span id="result"></span></div>
    </div>

  </div>

</div>


<script src="https://code.jquery.com/jquery-3.3.1.js"></script> <!-- Import Jquery Here-->
<script type="text/javascript">
$(document).ready(function() {
  $('#flexSwitchCheckChecked').change(function() {
      $.post("{% url 'sns:toggle' %}", {
          filter_toxic: this.checked, 
          csrfmiddlewaretoken: '{{ csrf_token }}'           
        },
        function(data){
          var self = document.getElementById("result");
          self.innerText = data.message;
          setTimeout(function() {
              self.innerText = '';
          }, 2000);                  
        }
      );
  });
}); 
</script>

{% endblock content %}

sns/templates/sns/wordfilter.html
{% extends "sns/page_base.html" %}


{% load static %}

{% block scripts %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'sns/wordfilter.css' %}">
{% endblock scripts %}

{% block content %}

<!-- MIDDLE-CONTAINER -->
<div class="middle-container container">
  <div class="togglediv block">
    <h1 class="titular"><span class="icon"></span>Choose Your Word Filters</h1>
    <div class="togglequestion">
      <h2>  Enter comma-separated values:  </h2>
      <form action="" method="post" id="wf-form">
        {% csrf_token %}
        <formgroup>
          {{ form.word_filters.errors }}

          {{ form.word_filters }}
          <div class="result"><span id="result"></span></div>
          <p class="instruction">  Comments closely matching these words will be filtered out of your feed.  </p>
        </formgroup>
        <input type="submit" class="btn btn-primary save-button" value="Save" />
      </form>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#wf-form').submit(function(e){
    $.post("{% url 'sns:wordfilter' %}",
      $(this).serialize(),
      function(data){
        var self = document.getElementById("result");
        self.innerText = data.message;
        setTimeout(function() {
            self.innerText = '';
        }, 2000);
      });
     e.preventDefault();
   });
});
</script>
{% endblock content %}